### PR TITLE
Testing against OpenMM dev/beta versions

### LINKED ISSUE #636: Test against openmm 8 beta
We should test against `openmm 8` beta, probably using the `conda-forge/label/openmm_dev` channel, since the `conda-forge/label/openmm_rc` has shown some problems. More info at: https://github.com/choderalab/perses/pull/1124

### PR DESCRIPTION
**Pull request by ijpulidos**
## Description
Testing against dev/beta versions of OpenMM. 

Using `conda-forge/label/openmm_dev` label.

Resolves #636 

## Todos
- [x] Implement feature / fix bug
- [ ] Add [tests](https://github.com/choderalab/openmmtools/tree/master/openmmtools/tests)
- [ ] Update [documentation](https://github.com/choderalab/openmmtools/tree/master/docs) as needed
- [ ] Update [changelog](https://github.com/choderalab/openmmtools/blob/master/docs/releasehistory.rst) to summarize changes in behavior, enhancements, and bugfixes implemented in this PR

## Status
- [ ] Ready to go

## Changelog message
```

```

### CODE REVIEW

**Comment by mikemhenry** [comment]
Good idea!

**Comment by mikemhenry** [comment]
Looks like we are running into the same bugs we saw in #628

**Comment by ijpulidos** [comment]
@mikemhenry The issue might be related, even though they look different from a first glance https://github.com/choderalab/openmmtools/actions/runs/3568138528/jobs/5996666286#step:8:2959

I also cannot reproduce this one locally, unlike the ones in https://github.com/choderalab/openmmtools/pull/628

**Comment by ijpulidos** [comment]
I cannot reproduce the issue locally, which suggests it is something different from https://github.com/choderalab/perses/pull/1124 (which I can reproduce locally)

**Comment by ijpulidos** [comment]
Closing, already implemented in #649 as far as I can see.

**Pull request closed without merging**
