### PR TITLE
Bring multistate samplers into openmmtools

### PR DESCRIPTION
**Pull request by jchodera**
This PR brings multistate samplers and the FIRE minimizer from YANK into `openmmtools`.

 - [x] Implement feature / fix bug
 - [x] Add [tests](https://github.com/choderalab/openmmtools/tree/master/openmmtools/tests)
 - [x] Update [documentation](https://github.com/choderalab/openmmtools/tree/master/docs) as needed
 - [x] Update [changelog](https://github.com/choderalab/openmmtools/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Comment by jchodera** [comment]
I've enabled sphinx builds for this branch, but it looks like they are failing:
https://readthedocs.org/projects/openmmtools/builds/8453444/

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/openmmtools/conda/multistate/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
ModuleNotFoundError: No module named 'sphinxcontrib.bibtex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/openmmtools/conda/multistate/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openmmtools/conda/multistate/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openmmtools/conda/multistate/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openmmtools/conda/multistate/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.bibtex (exception: No module named 'sphinxcontrib.bibtex')

Extension error:
Could not import extension sphinxcontrib.bibtex (exception: No module named 'sphinxcontrib.bibtex')
```
Looks like we need to add [`sphinxcontrib-bibtex`](https://anaconda.org/conda-forge/sphinxcontrib-bibtex) to [`docs/environment.yml`](https://github.com/choderalab/openmmtools/blob/56f2783d84dc1cd7f43f6ba311d3809496b62914/docs/environment.yml).

**Comment by hannahbrucemacdonald** [comment]
Will add that now, missed it because there's no docs/environment.yaml in yank

**Comment by hannahbrucemacdonald** [comment]
Will try figure out why the python 3.7 travis build is seg faulting, but I can't reproduce it locally

**Comment by jchodera** [comment]
You don't think switching to `pytest` would help, would it?

**Comment by hannahbrucemacdonald** [comment]
> You don't think switching to `pytest` would help, would it?

Happy to try switching over. I think the tests that use yield will need to be updated

**Comment by andrrizzi** [comment]
> You don't think switching to `pytest` would help, would it?

Possibly, I'm not sure. I'm still getting familiar with `pytest`'s features so I can't really give an estimate about how much time the conversion will take.

**Comment by jchodera** [comment]
Maybe we can do that switch as part of a larger overhaul to conform to the latest [cookiecutter](https://github.com/molssi/cookiecutter-cms) structure, after @andrrizzi has more time to get familiar with it?

**Comment by jchodera** [comment]
Multistate sampler docs are being built and pushed to [this branch of readthedocs](https://openmmtools.readthedocs.io/en/multistate/). You can see the API docs [here](https://openmmtools.readthedocs.io/en/multistate/sampling.html).

**Comment by jchodera** [comment]
@hannahbrucemacdonald : The docs you wrote in https://github.com/choderalab/openmmtools/pull/398/commits/239ab6804c435f3ad5b9cfe8f2a9acc0d2ea39db are fantastic! Thanks so much for adding this.

I'll just tack on the API docs to the end to make sure those are easy to find too.

**Comment by hannahbrucemacdonald** [comment]
> @hannahbrucemacdonald : The docs you wrote in [239ab68](https://github.com/choderalab/openmmtools/commit/239ab6804c435f3ad5b9cfe8f2a9acc0d2ea39db) are fantastic! Thanks so much for adding this.

The docs were from yank, so credit belongs to someone else!

**Comment by jchodera** [comment]
Apparently, the [default behavior for NetCDF changed in 1.4.0 to return masked arrays](http://unidata.github.io/netcdf4-python/#section6) if any energies are infinite. This requires we insert a ton of calls to change the default behavior whenever opening a dataset or creating a new variable (since the call to setting the default behavior only applies to *existing* variables, not new ones). I've tried to do this, but it's possible I've missed some places.

**Comment by jchodera** [comment]
> It seems that you've duplicated the mpiplus?
@hannahbrucemacdonald : Duplicated? I'm not quite sure what you mean. Did I accidentally include `mpiplus` in the recipe twice? Can you point to the line?

**Comment by jchodera** [comment]
I'm running into lots of HDF5 file issues now:
```
Doctest: openmmtools.multistate.multistatereporter.MultiStateReporter.read_dict ... HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140582073526080:
  #000: H5F.c line 444 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1364 in H5F__create(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #002: H5Fint.c line 1579 in H5F_open(): unable to truncate a file which is already open
    major: File accessibilty
    minor: Unable to open file
FAIL
```

**Comment by hannahbrucemacdonald** [comment]
> > It seems that you've duplicated the mpiplus?
> > @hannahbrucemacdonald : Duplicated? I'm not quite sure what you mean. Did I accidentally include `mpiplus` in the recipe twice? Can you point to the line?

https://github.com/choderalab/openmmtools/blob/5ed1773052bd1a788c19c1ce29d583297817ea1b/devtools/conda-recipe/meta.yaml#L30
https://github.com/choderalab/openmmtools/blob/5ed1773052bd1a788c19c1ce29d583297817ea1b/devtools/conda-recipe/meta.yaml#L33

**Comment by jchodera** [comment]
This is almost ready to be merged, @andrrizzi. I'm just solving some problems with SAMS tests that use the currently-unsupported non-global jumps, but I might just change that to global jump only and punt the rest of the local jump to later.

**Comment by jchodera** [comment]
Correction: The failing tests are with SAMS and *global* jump, and started when we upgraded the NetCDF libraries to a version that uses masked arrays by default. However, I think this may have revealed a bug in the old SAMS analysis implementation. Will be important to see if we can fix this.

**Comment by jchodera** [comment]
I think I've sorted this. If tests pass, this should be ready to merge.

**Comment by jchodera** [comment]
Yay! Travis tests pass now.

Windows tests fail because `drand48()` doesn't exist in windows, and this causes the `cython` compile of `_mix_replicas` to [fail](https://ci.appveyor.com/project/jchodera/openmmtools/builds/22071673/job/kj2bx30edgfm2f2w#L529). We can later fix this by instead [using the C++11 standard library](https://stackoverflow.com/questions/40976880/canonical-way-to-generate-random-numbers-in-cython/40992452), but we aren't supporting windows now.

**Comment by jchodera** [comment]
The docs build on readthedocs now!
The travis failure is the stochastic barostat segfault, so I'll merge this now.

**Pull request merged**
