### PR TITLE
Fix problematic testsystems

### PR DESCRIPTION
**Pull request by jchodera**
I'm starting to fix some problematic test systems in `openmmtools.testsystems` that had large potential energies associated with them, since these would generally lead to large energy differences between platforms.

### CODE REVIEW

**Comment by jchodera** [comment]
Eventually, we can store serialized XML versions of minimized/equilibrated forms of these systems, but it would be useful to at least have reasonable programmatically-generated initial conditions (which is what we try to do now).

**Comment by kyleabeauchamp** [comment]
So for the LJ box, I presume another way to build a starting box might be to treat the particles as hard spheres and use a sphere packer (for example https://pypi.python.org/pypi/spack).

**Comment by rmcgibbo** [comment]
Isn't this what packmol is for?

**Comment by kyleabeauchamp** [comment]
Yeah, I suppose I could do that too.

**Comment by jchodera** [comment]
Is PackMol deterministic?

Currently, I use subrandom sequences or grids.

**Comment by rmcgibbo** [comment]
I don't recall -- I suspect it is not, but that's mostly a guess.

**Comment by rmcgibbo** [comment]
If it's non-deterministic only due the use of a PRNG, it may be possible to simply fix the seed, which would accomplish the same purpose.

**Comment by kyleabeauchamp** [comment]
It looks like the only remaining test failure is explicit solvent src, which is already slated for renovation.  I'm going to merge the current work so I can file a new pr.

**Comment by jchodera** [comment]
Whoops, this wasn't ready to merge yet---sorry for not marking it WIP!

**Comment by jchodera** [comment]
> It looks like the only remaining test failure is explicit solvent src, which is already slated for renovation. I'm going to merge the current work so I can file a new pr.

I've got a more general fix for `src-explicit`.  Let me open this.

**Pull request merged**
