### PR TITLE
Disable Windows CI

### PR DESCRIPTION
**Pull request by mjw99**
## Description
Disable the Windows CI since it is failing (see #567). Aim to fix this on a branch and re-enable later on.

## Todos
- [x] Implement feature / fix bug

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by mikemhenry** [comment]
Good idea! Do you have a windows computer or VM to investigate why openmm might be having this issue? I'm wondering if we need to communicate upstream that there are issues with the windows build

**Comment by mikemhenry** [comment]
Oh and I'm not sure if you have access to do this or not, but in the repo settings we need to remove the windows CI from the required checks.

**Comment by mjw99** [comment]
Yes, I have a win10 image in my VirtualBox on my linux desktop; I can start to have a play there.

**Comment by ijpulidos** [comment]
I remember trying this in a windows VM this a few days ago and as far as I can tell the build `py38hb8327ec_1` (for python 3.8) of `openmm` is having issues.

On the other hand, the `openmm 7.7.0 py39h6dc0912_1` (for py 3.9) doesn't show the issues. I think it doesn't hurt to communicate the issues with some builds upstream.

**Comment by ijpulidos** [comment]
Wouldn't it be enough to mark the CI job as optional in this case? Since I think it helps the `openmm` folks that we are testing these configurations.

**Comment by mjw99** [comment]
> Wouldn't it be enough to mark the CI job as optional in this case? Since I think it helps the openmm folks that we are testing these configurations.

I think that would be a good idea; I did not know that was possible.

**Comment by ijpulidos** [comment]
Thanks for bringing this up! This had to be done changing the branch settings for the repository. I have changed this already. Feel free to close.

**Comment by mjw99** [comment]
> Thanks for bringing this up! This had to be done changing the branch settings for the repository. I have changed this already. Feel free to close.

Awesome; thanks Iván. I think I was struggling with some of the CI.yml syntax.

**Pull request closed without merging**
