### PR TITLE
remove cython from setup.py

### PR DESCRIPTION
**Pull request by mikemhenry**
## Description
Remove cython from setup.py

## Todos
- [ ] Implement feature / fix bug
- [ ] Add [tests](https://github.com/choderalab/openmmtools/tree/master/openmmtools/tests)
- [ ] Update [documentation](https://github.com/choderalab/openmmtools/tree/master/docs) as needed
- [ ] Update [changelog](https://github.com/choderalab/openmmtools/blob/master/docs/releasehistory.rst)Notable points that this PR has either accomplished or will accomplish.

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by mikemhenry** [comment]
@jaimergp anything else that should end up in this PR?

Regardless on what we decide on https://github.com/conda-forge/openmmtools-feedstock/pull/6 we should make a 0.20.2 release that does things better!

**Comment by jaimergp** [comment]
Now that you mention it, I'd like to remove the `six` dependency. We claim to support Pyrthon 3.6+ only, but https://github.com/choderalab/openmmtools/blob/master/openmmtools/sobol.py has this weird `xrange` py2k->py3k leftover. Removing that `six` import and replacing `range` with `xrange` would be nice to have here too.

**Comment by Lnaden** [comment]
> six import and replacing `range` with `xrange`

Did you mean "replacing `xrange` with `range`" instead?

**Comment by jaimergp** [comment]
> > six import and replacing `range` with `xrange`
> 
> Did you mean "replacing `xrange` with `range`" instead?

Oops, yes, exactly.

**Comment by mikemhenry** [comment]
That sounds good, I don't want to explode this release too much since there is some python 2.7 cruft (see `openmmtools/utils.py` line 691) But I can remove the dependency and use range.

**Comment by Lnaden** [comment]
> (see openmmtools/utils.py line 691)

That works for Py3 as well, so there isnt explicit harm in leaving it for now, but it probably could be cleaned up at a future time. 

> But I can remove the dependency and use range.

Yes to this. Anything which further and fully severs our ties to Python 2 the better, that is until we have to start using `twelve`.

**Comment by mikemhenry** [comment]
Agreed! I'll add @jaimergp and @Lnaden as reviewers -- let me know if there are any more changes you think we should make.

**Review by Lnaden — APPROVED** [review]
LGTM. We'll keep this simple and move on.

**Comment by jaimergp** [comment]
We should note that the last conda-forge release depends on `ambertools`, which is not available on Windows. I am not sure where this is used in the package, but maybe it should be reassessed? If we have find something, we need soft-imports and safeguards for missing executables. 

There's also another `xrange` instance in `openmmtools/scripts/test_openmm_platforms.py`.

**Comment by Lnaden** [comment]
The ambertools stuff comes from the `data` dirs: `https://github.com/choderalab/openmmtools/tree/483765d3b87395834745e79275469ce6c2c3fa13/openmmtools/data`

**Comment by jaimergp** [comment]
Those scripts are not run often, right?

**Comment by jaimergp** [comment]
I am also seeing `mdtraj` and `pandas` required in `testsystems`, but they are try-except guarded. The OpenEye toolkit is also there, but not available on `conda-forge`.

**Comment by mikemhenry** [comment]
> There's also another `xrange` instance in `openmmtools/scripts/test_openmm_platforms.py`.

I don't see it? What line?

**Comment by mikemhenry** [comment]
> The OpenEye toolkit is also there, but not available on `conda-forge`.

I dug a bit and while that will throw an error -- it isn't clear to me how to trivially replace the functionality or disable the functionality (it is really limited in use and a quick grok shows that it is used in test systems) but I can throw a different error if we want other than the one openeye will throw when it says it is unlicensed. 

Is this fix something you wanted in this patch or can we make this an issue for another day @jaimergp ?

**Comment by jaimergp** [comment]
> I don't see it? What line?

Ah, you got it already! Disregard then.

> Is this fix something you wanted in this patch or can we make this an issue for another day?

Definitely a different issue.

**Comment by mikemhenry** [comment]
Okay! I will merge this and cut a new release, thank you both for all of your help!

**Comment by mikemhenry** [comment]
ALMOST FORGOT TO UPDATE THE CHANGELOG!

**Pull request merged**
