### PR TITLE
test-openmm-platforms is now installed as a command-line script

### PR DESCRIPTION
**Pull request by jchodera**
`test-openmm-platforms` is now installed as a command-line script since this may be useful for debugging issues with hardware or software OpenMM installations.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Looks good to me, can merge after travis

**Comment by jchodera** [comment]
Should we have a nosetest for this as well?  I could even refactor this into a nosetest and a script that calls the nosetest...

**Comment by kyleabeauchamp** [comment]
IMHO we can punt on nosetests for now

**Comment by kyleabeauchamp** [comment]
Looks like we need to fix print statements for py3k

**Comment by jchodera** [comment]
I'm getting this error:
```
DHFRExplicit
DHFR test system requires Parmed (`import chemistry`).
Traceback (most recent call last):
  File "/Users/choderaj/anaconda/bin//test-openmm-platforms", line 9, in <module>
    load_entry_point('openmmtools==0.6.2', 'console_scripts', 'test-openmm-platforms')()
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/openmmtools-0.6.2-py2.7.egg/openmmtools/scripts/test_openmm_platforms.py", line 211, in main
    testsystem = constructor()
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/openmmtools-0.6.2-py2.7.egg/openmmtools/testsystems.py", line 2569, in __init__
    raise(e)
ImportError: No module named chemistry
```
We should be requiring ParmEd as a dependency now.  @kyleabeauchamp : Can you create a PR to do that?

**Comment by kyleabeauchamp** [comment]
It's not available as a conda recipe yet.  

All of our nose tests have try except clauses that take care of optional dependencies.

**Comment by kyleabeauchamp** [comment]
I think we should just keep this as an optional dependency until parmed has a conda release.

**Comment by jchodera** [comment]
> It's not available as a conda recipe yet.

I think this was just waiting on the (now complete) release of AmberTools 15, right?  Should we wrap this now?

**Comment by jchodera** [comment]
> I think we should just keep this as an optional dependency until parmed has a conda release.

This would mean we have to rejigger our whole testing framework, would it not?  We need a different way of discriminating between failing test cases and optional tests that fail due to missing dependencies.  Any ideas?

**Comment by jchodera** [comment]
> All of our nose tests have try except clauses that take care of optional dependencies.

Ah, OK.  I missed that.  Can you give a pointer to an example of the idiom for handling this?

**Comment by kyleabeauchamp** [comment]
https://github.com/choderalab/openmmtools/blob/master/openmmtools/tests/test_testsystems.py#L55

**Comment by jchodera** [comment]
Thanks!  That should do the trick for now.

Added a (simple) nosetest too, but not sure if this will cause a timeout.

**Comment by jchodera** [comment]
The `--nocapture` flag doesn't seem to be working.

**Comment by kyleabeauchamp** [comment]
Hmm, the tests seem OK otherwise--there are just some test failures with energy differences...

**Comment by jchodera** [comment]
Oh, sorry!  I didn't see the output---you're right that it's there.

I'll go ahead and merge this then, and we can either fix the test systems that are causing problems or file bug reports for OpenMM if these are not `openmmtools` bugs.

**Pull request merged**
