### PR TITLE
Fix failing CI tests

### PR DESCRIPTION
**Pull request by jchodera**
## Description
This PR fixes failing tests by
* Changing the behavior of `openmmtools.utils.available_platforms()` to filter by minimum available precision, which defaults to `mixed`
* Changing the behavior of `openmmtools.utils.temporary_directory()` to issue a warning (instead of an Exception) if the temporary directory fails at being cleaned up

## Todos
- [x] Implement feature / fix bug
- [x] Add [tests](https://github.com/choderalab/openmmtools/tree/master/openmmtools/tests)
- [x] Update [documentation](https://github.com/choderalab/openmmtools/tree/master/docs) as needed
- [x] Update [changelog](https://github.com/choderalab/openmmtools/blob/master/docs/releasehistory.rst)Notable points that this PR has either accomplished or will accomplish.

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by jchodera** [comment]
The `osx` issue seems to be that the OpenCL platform is available, but doesn't support all the kernels requested when we create a `Context`, so fails. I can change the tests to let this behavior pass for now, but we really need a way to iterate through platforms that are capable of supporting the system and integrator in the future, or gracefully falling back to the next best platform.
```
======================================================================
ERROR: Test configuration of the context cache.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/miniconda/envs/test/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/runner/work/openmmtools/openmmtools/openmmtools/tests/test_mcmc.py", line 257, in test_context_cache
    move.apply(thermodynamic_state, sampler_state)
  File "/Users/runner/work/openmmtools/openmmtools/openmmtools/mcmc.py", line 1120, in apply
    super(LangevinDynamicsMove, self).apply(thermodynamic_state, sampler_state)
  File "/Users/runner/work/openmmtools/openmmtools/openmmtools/mcmc.py", line 661, in apply
    context, integrator = context_cache.get_context(thermodynamic_state, integrator)
  File "/Users/runner/work/openmmtools/openmmtools/openmmtools/cache.py", line 761, in get_context
    context = thermodynamic_state.create_context(integrator, self.platform)
  File "/Users/runner/work/openmmtools/openmmtools/openmmtools/states.py", line 1181, in create_context
    return openmm.Context(system, integrator, platform)
  File "/usr/local/miniconda/envs/test/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 6270, in __init__
    this = _openmm.new_Context(*args)
Exception: No compatible OpenCL platform is available

======================================================================
ERROR: ThermodynamicState.create_context() method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/miniconda/envs/test/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/runner/work/openmmtools/openmmtools/openmmtools/tests/test_states.py", line 648, in test_method_create_context
    context = state.create_context(integrator, platform)
  File "/Users/runner/work/openmmtools/openmmtools/openmmtools/states.py", line 1181, in create_context
    return openmm.Context(system, integrator, platform)
  File "/usr/local/miniconda/envs/test/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 6270, in __init__
    this = _openmm.new_Context(*args)
Exception: No compatible OpenCL platform is available
```

**Comment by jchodera** [comment]
I've dealt with the OpenCL platform issue by changing the behavior of `openmmtools.utils.available_platforms()` to filter by minimum available precision, which defaults to `mixed`.

**Comment by jchodera** [comment]
Everything passes except the OpenMM nightly builds! 

It looks like there is an issue with `integrator.__get_state__()`:
```
======================================================================
FAIL: ContextCache._copy_integrator_state correctly copies state.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/runner/work/openmmtools/openmmtools/openmmtools/tests/test_cache.py", line 212, in test_copy_integrator_state
    assert integrator1.__getstate__() == integrator2.__getstate__()
```
We'll address that separately.

**Comment by jaimergp** [comment]
Regarding `openmmtools.utils.temporary_directory()` you might want to try https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory, which handles this natively. On Windows, there's a chance the file descriptors need to be closed prior to unlink. [See here](https://stackoverflow.com/a/50520072/3407590).

**Comment by Lnaden** [comment]
> tempfile.TemporaryDirectory

I imagine that will be a much safer option. We didn't have that function back in Python 2.7, so I think that's where the util function came from.

**Pull request merged**
