### PR TITLE
Fixes for SrcImplicit and SrcExplicit

### PR DESCRIPTION
**Pull request by jchodera**
I've created a simple script to retrieve a PDB file and generate an energy-minimized system.

Regenerating the Src examples now.

### CODE REVIEW

**Comment by jchodera** [comment]
Looks like I've at least accomplished the goal of getting the energies to be reasonable:
```
SrcImplicit
                       Reference    -16470.832346 kcal/mol         0.000000 kcal/mol        37.793317 kcal/mol         0.000000 kcal/mol
                             CPU    -16470.784782 kcal/mol         0.047563 kcal/mol        37.793378 kcal/mol         0.000742 kcal/mol
                            CUDA    -16470.738563 kcal/mol         0.093783 kcal/mol        37.793540 kcal/mol         0.020611 kcal/mol
                                 WARNING: Potential energy error (0.093783 kcal/mol) exceeds tolerance (0.060000 kcal/mol).  Test failed.
                          OpenCL    -16470.737422 kcal/mol         0.094924 kcal/mol        37.793537 kcal/mol         0.020609 kcal/mol
                                 WARNING: Potential energy error (0.094924 kcal/mol) exceeds tolerance (0.060000 kcal/mol).  Test failed.
Writing failed test system to 'SrcImplicit'.{system,state}.xml ...
Breakdown of discrepancies by Force component:
HarmonicBondForce
                        platform        potential                     error                 force mag                 rms error
                       Reference       265.157577 kcal/mol         0.000000 kcal/mol        81.432201 kcal/mol         0.000000 kcal/mol
                             CPU       265.157577 kcal/mol         0.000000 kcal/mol        81.432201 kcal/mol         0.000000 kcal/mol
                            CUDA       265.157216 kcal/mol        -0.000360 kcal/mol        81.432072 kcal/mol         0.016055 kcal/mol
                          OpenCL       265.157216 kcal/mol        -0.000360 kcal/mol        81.432072 kcal/mol         0.016055 kcal/mol
HarmonicAngleForce
                        platform        potential                     error                 force mag                 rms error
                       Reference       876.743418 kcal/mol         0.000000 kcal/mol        76.935694 kcal/mol         0.000000 kcal/mol
                             CPU       876.743418 kcal/mol         0.000000 kcal/mol        76.935694 kcal/mol         0.000000 kcal/mol
                            CUDA       876.745643 kcal/mol         0.002225 kcal/mol        76.935899 kcal/mol         0.007471 kcal/mol
                          OpenCL       876.745399 kcal/mol         0.001981 kcal/mol        76.935889 kcal/mol         0.007468 kcal/mol
PeriodicTorsionForce
                        platform        potential                     error                 force mag                 rms error
                       Reference      4250.268623 kcal/mol         0.000000 kcal/mol        24.420276 kcal/mol         0.000000 kcal/mol
                             CPU      4250.268623 kcal/mol         0.000000 kcal/mol        24.420276 kcal/mol         0.000000 kcal/mol
                            CUDA      4250.268628 kcal/mol         0.000005 kcal/mol        24.420218 kcal/mol         0.002035 kcal/mol
                          OpenCL      4250.268480 kcal/mol        -0.000143 kcal/mol        24.420214 kcal/mol         0.002035 kcal/mol
NonbondedForce
                        platform        potential                     error                 force mag                 rms error
                       Reference    -17371.716704 kcal/mol         0.000000 kcal/mol        83.577596 kcal/mol         0.000000 kcal/mol
                             CPU    -17371.704718 kcal/mol         0.011986 kcal/mol        83.577594 kcal/mol         0.000390 kcal/mol
GBSAOBCForce
                        platform        potential                     error                 force mag                 rms error
                       Reference     -4491.285260 kcal/mol         0.000000 kcal/mol        46.782111 kcal/mol         0.000000 kcal/mol
                             CPU     -4491.249683 kcal/mol         0.035578 kcal/mol        46.782130 kcal/mol         0.000645 kcal/mol
CMMotionRemover
                        platform        potential                     error                 force mag                 rms error
                       Reference         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
                             CPU         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
                            CUDA         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
                          OpenCL         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol

SrcExplicit
                       Reference   -278504.231592 kcal/mol         0.000000 kcal/mol       265.946679 kcal/mol         0.000000 kcal/mol
                             CPU   -278502.325557 kcal/mol         1.906035 kcal/mol       265.946846 kcal/mol         0.010746 kcal/mol
                                 WARNING: Potential energy error (1.906035 kcal/mol) exceeds tolerance (0.060000 kcal/mol).  Test failed.
                            CUDA   -278504.309659 kcal/mol        -0.078067 kcal/mol       265.946591 kcal/mol         0.011991 kcal/mol
                                 WARNING: Potential energy error (-0.078067 kcal/mol) exceeds tolerance (0.060000 kcal/mol).  Test failed.
                          OpenCL   -278504.312678 kcal/mol        -0.081086 kcal/mol       265.946592 kcal/mol         0.011952 kcal/mol
                                 WARNING: Potential energy error (-0.081086 kcal/mol) exceeds tolerance (0.060000 kcal/mol).  Test failed.
Writing failed test system to 'SrcExplicit'.{system,state}.xml ...
Breakdown of discrepancies by Force component:
HarmonicBondForce
                        platform        potential                     error                 force mag                 rms error
                       Reference       241.355704 kcal/mol         0.000000 kcal/mol        24.533954 kcal/mol         0.000000 kcal/mol
                             CPU       241.355704 kcal/mol         0.000000 kcal/mol        24.533954 kcal/mol         0.000000 kcal/mol
                            CUDA       241.355910 kcal/mol         0.000206 kcal/mol        24.533902 kcal/mol         0.004766 kcal/mol
                          OpenCL       241.355910 kcal/mol         0.000206 kcal/mol        24.533902 kcal/mol         0.004766 kcal/mol
HarmonicAngleForce
                        platform        potential                     error                 force mag                 rms error
                       Reference       930.825886 kcal/mol         0.000000 kcal/mol        24.503043 kcal/mol         0.000000 kcal/mol
                             CPU       930.825886 kcal/mol         0.000000 kcal/mol        24.503043 kcal/mol         0.000000 kcal/mol
                            CUDA       930.826165 kcal/mol         0.000279 kcal/mol        24.503047 kcal/mol         0.002280 kcal/mol
                          OpenCL       930.825942 kcal/mol         0.000056 kcal/mol        24.503044 kcal/mol         0.002280 kcal/mol
PeriodicTorsionForce
                        platform        potential                     error                 force mag                 rms error
                       Reference      4370.242637 kcal/mol         0.000000 kcal/mol         8.505245 kcal/mol         0.000000 kcal/mol
                             CPU      4370.242637 kcal/mol        -0.000000 kcal/mol         8.505245 kcal/mol         0.000000 kcal/mol
                            CUDA      4370.242513 kcal/mol        -0.000124 kcal/mol         8.505225 kcal/mol         0.000682 kcal/mol
                          OpenCL      4370.242327 kcal/mol        -0.000310 kcal/mol         8.505224 kcal/mol         0.000682 kcal/mol
NonbondedForce
                        platform        potential                     error                 force mag                 rms error
                       Reference   -284046.655818 kcal/mol         0.000000 kcal/mol       267.024399 kcal/mol         0.000000 kcal/mol
                             CPU   -284044.749725 kcal/mol         1.906094 kcal/mol       267.024565 kcal/mol         0.010746 kcal/mol
                            CUDA   -284046.737638 kcal/mol        -0.081819 kcal/mol       267.024311 kcal/mol         0.010281 kcal/mol
                          OpenCL   -284046.735535 kcal/mol        -0.079717 kcal/mol       267.024311 kcal/mol         0.010236 kcal/mol
CMMotionRemover
                        platform        potential                     error                 force mag                 rms error
                       Reference         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
                             CPU         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
                            CUDA         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
                          OpenCL         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
```

**Comment by kyleabeauchamp** [comment]
Very interesting that the CPU platform is 2 kcal / mol different.  

Otherwise, things look good to me.  

Perhaps we want to hard-code in dictionary of exceptions or looser tolerances for `src` so that Travis doesn't return constant failures, though?

**Comment by jchodera** [comment]
> Perhaps we want to hard-code in dictionary of exceptions or looser tolerances for src so that Travis doesn't return constant failures, though?

I think we just need to get this fixed in OpenMM.  2 kcal/mol errors will cause huge problems for YANK

**Comment by kyleabeauchamp** [comment]
Sounds good

**Comment by jchodera** [comment]
Yeah, it's odd that the CPU energies are 2 kcal/mol different for `NonbondedForce`, but the forces are pretty good...

**Comment by jchodera** [comment]
The Src implicit solvent energies are a bit too discrepant (0.09 kcal/mol) on CUDA and OpenCL.  What's odd is that the breakdown by energy component doesn't actually print the CUDA and OpenCL platform values for `NonbondedForce` and `GBSAOBCForce`.  It must be triggering some sort of exception when I try to compute just these force components.

**Comment by jchodera** [comment]
It looks like OpenMM won't let me break up the `NonbondedForce` and `GBSAOBCForce` into separate force groups to decompose energies:
```
NonbondedForce
                        platform        potential                     error                 force mag                 rms error
                       Reference    -17371.716704 kcal/mol         0.000000 kcal/mol        83.577596 kcal/mol         0.000000 kcal/mol
                             CPU    -17371.704718 kcal/mol         0.011986 kcal/mol        83.577594 kcal/mol         0.000389 kcal/mol
All nonbonded forces must be in the same force group
All nonbonded forces must be in the same force group
```

**Comment by kyleabeauchamp** [comment]
So the relative difference on those two is ~7E-7.  I'm not sure we can expect any better than that, right?

**Comment by jchodera** [comment]
> So the relative difference on those two is ~7E-7. I'm not sure we can expect any better than that, right?

For `SrcImplicit`?  The CPU platform (which uses single precision, I think) does get much smaller energy errors.  So I believe it should be possible to do better than this.

**Comment by rmcgibbo** [comment]
Suggestion: for PME, you should print the breakdown of the energy/forces from the reciprocal space vs. real space, since they can be assigned to separate force groups. For the SrcExplicit on my machine,  they break down line

```
Real space:
Reference 890376.7051477302 kcal/mol
      CPU 890378.6407856604 kcal/mol

Reciprocal space
Reference -1174423.3609660787 kcal/mol
      CPU -1174423.4197082222 kcal/mol
```

**Comment by jchodera** [comment]
> Suggestion: for PME, you should print the breakdown of the energy/forces from the reciprocal space vs. real space, since they can be assigned to separate force groups. 

Excellent idea!

**Comment by jchodera** [comment]
It seems that the CUDA and OpenCL platforms won't let me break up some forces into different groups when GB forces are in use, though it *will* let me break things into different groups when using explicit solvent.  Any idea what the actual restriction is?  Clearly the exception message "All nonbonded foces must be in the same group" is not precisely correct.

Implicit:
```
SrcImplicit
       Reference          double    -16470.832346 kcal/mol         0.000000 kcal/mol        37.793317 kcal/mol         0.000000 kcal/mol
             CPU          single    -16470.784782 kcal/mol         0.047563 kcal/mol        37.793377 kcal/mol         0.000742 kcal/mol
All nonbonded forces must be in the same force group
All nonbonded forces must be in the same force group
```
but
```
SrcExplicit
       Reference          double   -278504.231592 kcal/mol         0.000000 kcal/mol       265.946679 kcal/mol         0.000000 kcal/mol
             CPU          single   -278502.325382 kcal/mol         1.906210 kcal/mol       265.946846 kcal/mol         0.010746 kcal/mol
                                 WARNING: Potential energy error (1.906210 kcal/mol) exceeds tolerance (0.060000 kcal/mol).  Test failed.
            CUDA          single   -278504.313345 kcal/mol        -0.081753 kcal/mol       265.946591 kcal/mol         0.011991 kcal/mol
                                 WARNING: Potential energy error (-0.081753 kcal/mol) exceeds tolerance (0.060000 kcal/mol).  Test failed.
            CUDA          double   -278504.256726 kcal/mol        -0.025134 kcal/mol       265.946669 kcal/mol         0.009967 kcal/mol
          OpenCL          single   -278504.309139 kcal/mol        -0.077547 kcal/mol       265.946592 kcal/mol         0.011952 kcal/mol
                                 WARNING: Potential energy error (-0.077547 kcal/mol) exceeds tolerance (0.060000 kcal/mol).  Test failed.
          OpenCL          double   -278504.254205 kcal/mol        -0.022612 kcal/mol       265.946669 kcal/mol         0.009972 kcal/mol
Writing failed test system to 'SrcExplicit'.{system,state}.xml ...
Breakdown of discrepancies by Force component:
HarmonicBondForce
        platform       precision        potential                     error                 force mag                 rms error
       Reference          single       241.355704 kcal/mol         0.000000 kcal/mol        24.533954 kcal/mol         0.000000 kcal/mol
       Reference          double       241.355704 kcal/mol         0.000000 kcal/mol        24.533954 kcal/mol         0.000000 kcal/mol
             CPU          single       241.355704 kcal/mol         0.000000 kcal/mol        24.533954 kcal/mol         0.000000 kcal/mol
             CPU          double       241.355704 kcal/mol         0.000000 kcal/mol        24.533954 kcal/mol         0.000000 kcal/mol
            CUDA          single       241.355910 kcal/mol         0.000206 kcal/mol        24.533902 kcal/mol         0.004766 kcal/mol
            CUDA          double       241.355913 kcal/mol         0.000209 kcal/mol        24.533955 kcal/mol         0.000093 kcal/mol
          OpenCL          single       241.355910 kcal/mol         0.000206 kcal/mol        24.533902 kcal/mol         0.004766 kcal/mol
          OpenCL          double       241.355913 kcal/mol         0.000209 kcal/mol        24.533955 kcal/mol         0.000093 kcal/mol
HarmonicAngleForce
        platform       precision        potential                     error                 force mag                 rms error
       Reference          single       930.825886 kcal/mol         0.000000 kcal/mol        24.503043 kcal/mol         0.000000 kcal/mol
       Reference          double       930.825886 kcal/mol         0.000000 kcal/mol        24.503043 kcal/mol         0.000000 kcal/mol
             CPU          single       930.825886 kcal/mol         0.000000 kcal/mol        24.503043 kcal/mol         0.000000 kcal/mol
             CPU          double       930.825886 kcal/mol         0.000000 kcal/mol        24.503043 kcal/mol         0.000000 kcal/mol
            CUDA          single       930.826165 kcal/mol         0.000279 kcal/mol        24.503047 kcal/mol         0.002280 kcal/mol
            CUDA          double       930.826266 kcal/mol         0.000380 kcal/mol        24.503051 kcal/mol         0.000027 kcal/mol
          OpenCL          single       930.825942 kcal/mol         0.000056 kcal/mol        24.503044 kcal/mol         0.002280 kcal/mol
          OpenCL          double       930.826266 kcal/mol         0.000380 kcal/mol        24.503051 kcal/mol         0.000027 kcal/mol
PeriodicTorsionForce
        platform       precision        potential                     error                 force mag                 rms error
       Reference          single      4370.242637 kcal/mol         0.000000 kcal/mol         8.505245 kcal/mol         0.000000 kcal/mol
       Reference          double      4370.242637 kcal/mol         0.000000 kcal/mol         8.505245 kcal/mol         0.000000 kcal/mol
             CPU          single      4370.242637 kcal/mol        -0.000000 kcal/mol         8.505245 kcal/mol         0.000000 kcal/mol
             CPU          double      4370.242637 kcal/mol        -0.000000 kcal/mol         8.505245 kcal/mol         0.000000 kcal/mol
            CUDA          single      4370.242513 kcal/mol        -0.000124 kcal/mol         8.505225 kcal/mol         0.000682 kcal/mol
            CUDA          double      4370.242652 kcal/mol         0.000015 kcal/mol         8.505245 kcal/mol         0.000006 kcal/mol
          OpenCL          single      4370.242327 kcal/mol        -0.000310 kcal/mol         8.505224 kcal/mol         0.000682 kcal/mol
          OpenCL          double      4370.242480 kcal/mol        -0.000157 kcal/mol         8.505242 kcal/mol         0.000013 kcal/mol
NonbondedForce (direct)
        platform       precision        potential                     error                 force mag                 rms error
       Reference          single    890376.705148 kcal/mol         0.000000 kcal/mol       266.863615 kcal/mol         0.000000 kcal/mol
       Reference          double    890376.705148 kcal/mol         0.000000 kcal/mol       266.863615 kcal/mol         0.000000 kcal/mol
             CPU          single    890378.624820 kcal/mol         1.919672 kcal/mol       266.863810 kcal/mol         0.001965 kcal/mol
             CPU          double    890378.624820 kcal/mol         1.919672 kcal/mol       266.863810 kcal/mol         0.001965 kcal/mol
            CUDA          single    890376.654188 kcal/mol        -0.050960 kcal/mol       266.863533 kcal/mol         0.002431 kcal/mol
            CUDA          double    890376.724715 kcal/mol         0.019567 kcal/mol       266.863614 kcal/mol         0.000016 kcal/mol
          OpenCL          single    890376.673893 kcal/mol        -0.031255 kcal/mol       266.863534 kcal/mol         0.002247 kcal/mol
          OpenCL          double    890376.727418 kcal/mol         0.022270 kcal/mol       266.863614 kcal/mol         0.000319 kcal/mol
NonbondedForce (reciprocal)
        platform       precision        potential                     error                 force mag                 rms error
       Reference          single  -1174423.360966 kcal/mol         0.000000 kcal/mol         8.867282 kcal/mol         0.000000 kcal/mol
       Reference          double  -1174423.360966 kcal/mol         0.000000 kcal/mol         8.867282 kcal/mol         0.000000 kcal/mol
             CPU          single  -1174423.374486 kcal/mol        -0.013520 kcal/mol         8.867285 kcal/mol         0.010555 kcal/mol
             CPU          double  -1174423.374486 kcal/mol        -0.013520 kcal/mol         8.867285 kcal/mol         0.010555 kcal/mol
            CUDA          single  -1174423.405924 kcal/mol        -0.044958 kcal/mol         8.867237 kcal/mol         0.009973 kcal/mol
            CUDA          double  -1174423.406272 kcal/mol        -0.045306 kcal/mol         8.867232 kcal/mol         0.009967 kcal/mol
          OpenCL          single  -1174423.406744 kcal/mol        -0.045778 kcal/mol         8.867231 kcal/mol         0.009970 kcal/mol
          OpenCL          double  -1174423.406281 kcal/mol        -0.045315 kcal/mol         8.867232 kcal/mol         0.009967 kcal/mol
CMMotionRemover
        platform       precision        potential                     error                 force mag                 rms error
       Reference          single         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
       Reference          double         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
             CPU          single         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
             CPU          double         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
            CUDA          single         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
            CUDA          double         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
          OpenCL          single         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
          OpenCL          double         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol
```

**Comment by jchodera** [comment]
I'm finding that the `CPU` platform hangs with `FlexibleWaterBox`, `FourSiteWaterBox`, and `FiveSiteWaterBox` unless I set `OPENMM_CPU_THREADS` to 1.  Will debug this further later.

**Comment by jchodera** [comment]
These tests are now working as intended, so I am going to merge this.

**Pull request merged**
