### PR TITLE
Fix pushing docs to readthedocs

### PR DESCRIPTION
**Pull request by andrrizzi**
Not sure if there's a way to test this without merging the PR, but this is an attempt to fix the readthedocs integration.

### CODE REVIEW

**Comment by jchodera** [comment]
Yes! Let me test.

**Comment by jchodera** [comment]
Building here: https://readthedocs.org/projects/openmmtools/builds/

**Comment by jchodera** [comment]
It works! 

https://openmmtools.readthedocs.io/en/fix-push-docs/

Go ahead and merge.

**Comment by andrrizzi** [comment]
Great, thanks!

**Pull request merged**
