### PR TITLE
logsumexp is now in scipy.special

### PR DESCRIPTION
**Pull request by jchodera**
`logsumexp` has been moved form `scipy.misc` to `scipy.special`.

 - [x] Implement feature / fix bug
 - [x] Update [changelog](https://github.com/choderalab/openmmtools/blob/master/docs/releasehistory.rst)

cc: https://github.com/choderalab/yank/pull/1162

### CODE REVIEW

**Comment by jchodera** [comment]
I'm struggling to figure out what is going on here:
```
Packaging openmmtools-dev
INFO:conda_build.build:Packaging openmmtools-dev
Packaging openmmtools-dev-0.0.0-py36_0
INFO:conda_build.build:Packaging openmmtools-dev-0.0.0-py36_0
compiling .pyc files...
number of files: 257
ERROR :: get_rpaths_raw()=[u'/home/travis/miniconda/conda-bld/openmmtools-dev_1558474080589/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib'] and patchelf=/home/travis/miniconda/conda-bld/openmmtools-dev_1558474080589/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib disagree for /home/travis/miniconda/conda-bld/openmmtools-dev_1558474080589/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.6/site-packages/openmmtools-0.19.0-py3.6-linux-x86_64.egg/openmmtools/multistate/mixing/_mix_replicas.cpython-36m-x86_64-linux-gnu.so :: 
WARNING (openmmtools-dev,lib/python3.6/site-packages/openmmtools-0.19.0-py3.6-linux-x86_64.egg/openmmtools/multistate/mixing/_mix_replicas.cpython-36m-x86_64-linux-gnu.so): $RPATH/libc.so.6 not found in sysroot, is this binary repackaging? .. do you need to use install_name_tool/patchelf?
WARNING (openmmtools-dev,lib/python3.6/site-packages/openmmtools-0.19.0-py3.6-linux-x86_64.egg/openmmtools/multistate/mixing/_mix_replicas.cpython-36m-x86_64-linux-gnu.so): $RPATH/libpthread.so.0 not found in sysroot, is this binary repackaging? .. do you need to use install_name_tool/patchelf?
   INFO (openmmtools-dev): plugin library package conda-forge::cython-0.29.7-py36he1b5a44_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (openmmtools-dev): dso library package omnia::openmm-7.3.1-py36_cuda92_rc_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (openmmtools-dev): dso library package conda-forge::python-3.6.7-h381d211_1004 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
Fixing permissions
Detected hard-coded path in binary file lib/python3.6/site-packages/openmmtools-0.19.0-py3.6-linux-x86_64.egg/openmmtools/multistate/mixing/_mix_replicas.cpython-36m-x86_64-linux-gnu.so
Detected hard-coded path in text file bin/benchmark-alchemy
Detected hard-coded path in text file bin/test-openmm-platforms
Package verification results:
-----------------------------
/tmp/tmpvO4uiW/openmmtools-dev-0.0.0-py36_0.tar.bz2: C1115 Found invalid license "MIT License" in info/index.json
/tmp/tmpvO4uiW/openmmtools-dev-0.0.0-py36_0.tar.bz2: C1137 Found namespace file "lib/python3.6/site-packages/openmmtools.pth" in archive
/tmp/tmpvO4uiW/openmmtools-dev-0.0.0-py36_0.tar.bz2: C1139 Found pyc file "share/openmmtools/examples/integrator-benchmarks/__pycache__/integrator-benchmarks.cpython-36.pyc" in invalid directory
File format::   0%|          | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```
@andrrizzi @jaimergp any ideas?

**Comment by Lnaden** [comment]
I don't know what the base problem is per-se, but my first warning sign is that you are pulling down and trying to package a Python 3 package, with Python 2 Miniconda build. I know that multiprocessing and threading in 3 got way better, so I would first start with that to eliminate oddities and reduce fault points.

**Comment by jchodera** [comment]
Good point. We should just update everything to the new cookiecutter.

**Comment by jaimergp** [comment]
I agree with @Lnaden. Seeing that it is failing both in Travis and Appveyor, updating Miniconda to use Python3 would be my first guess. I would also clear the caches if there are any.

**Comment by jchodera** [comment]
Thanks for the suggestions!
I'm updating the build infrastructure to match the MolSSI cookiecutter in this PR:
https://github.com/choderalab/openmmtools/pull/424

**Comment by jchodera** [comment]
Superseded by #424

**Pull request closed without merging**
