### PR TITLE
Adding major contributors

### LINKED ISSUE #601: Update Major Contributors
We should add @ijpulidos @mikemhenry @zhang-ivy @dominicrufa to the [list of major contributors in the README](https://github.com/choderalab/openmmtools/blob/main/README.md#contributors).

### PR DESCRIPTION
**Pull request by ijpulidos**
## Description
Adding major contributors, namely @ijpulidos, @zhang-ivy, and @dominicrufa. Now using github profile links as reference.

Resolves #601 

## Todos
- [x] Implement feature / fix bug
- [ ] Add [tests](https://github.com/choderalab/openmmtools/tree/master/openmmtools/tests)
- [ ] Update [documentation](https://github.com/choderalab/openmmtools/tree/master/docs) as needed
- [ ] Update [changelog](https://github.com/choderalab/openmmtools/blob/master/docs/releasehistory.rst) to summarize changes in behavior, enhancements, and bugfixes implemented in this PR

## Status
- [ ] Ready to go

### CODE REVIEW

**Review by mikemhenry — APPROVED** [review]

**Comment by mikemhenry** [comment]
I like the switch to github usernames, are you okay with it @jchodera

**Comment by jchodera** [comment]
That's great, thanks!

In future, adding ORCID would also be useful.

**Review by jchodera — APPROVED** [review]

**Comment by zhang-ivy** [comment]
@ijpulidos Did we want to add @mikemhenry as well?

**Comment by mikemhenry** [comment]
Haha yes please 😊

**Comment by ijpulidos** [comment]
Yes! Of course! Sorry.

**Comment by mikemhenry** [comment]
No worries, I missed it in my review :rofl:

**Pull request merged**
