### PR TITLE
GHMCIntegrator fixes

### LINKED ISSUE #114: GHMCIntegrator is missing updateContext() call
We need to add an `updateContext()` call to [`GHMCIntegrator`](https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py#L526-L650)

### PR DESCRIPTION
**Pull request by jchodera**
* `GHMCIntegrator` now correctly calls `updateContextState()` to fix #114
* added `potential_old` and `potential_new` global variables
* move initialization steps into `beginIfBlock`

### CODE REVIEW

**Comment by jchodera** [comment]
Tagging @gregoryross for review.

**Comment by gregoryross** [comment]
Looks great! I'll test whether using `potential_old` and `potential_new` is faster than using 
```
state = context.getState(getEnergy=True)
pot_energy = state.getPotentialEnergy()
```

**Comment by jchodera** [comment]
OK, once this passes tests, I'll cut a new release and update the omnia recipe.

**Comment by jchodera** [comment]
Travis failure is just a timeout. Merging.

**Pull request merged**
