### PR TITLE
Ran pyflakes and autopep8 on constants, integrators, and testsystems

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
My text editor was complaining at a lot of things, so I figured it was time to do a round of cleanup.

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks!  

It's not recommended we automate this yet, right?

**Comment by kyleabeauchamp** [comment]
I personally would rather run it manually once a year than maintain more CI scripts for running these things.

**Comment by kyleabeauchamp** [comment]
OK, it looks like the only failure is src Explicit.

**Comment by jchodera** [comment]
Maybe we should raise the threshhold for those failures?

**Pull request merged**
