### PR TITLE
add HIP platform to openmmtools

### PR DESCRIPTION
**Pull request by mikemhenry**
## Description
Provide a brief description of the PR's purpose here.

## Todos
- [ ] Implement feature / fix bug
- [ ] Add [tests](https://github.com/choderalab/openmmtools/tree/master/openmmtools/tests)
- [ ] Update [documentation](https://github.com/choderalab/openmmtools/tree/master/docs) as needed
- [ ] Update [changelog](https://github.com/choderalab/openmmtools/blob/master/docs/releasehistory.rst) to summarize changes in behavior, enhancements, and bugfixes implemented in this PR

## Status
- [ ] Ready to go

## Changelog message
```

```

### CODE REVIEW

**Review by ijpulidos — APPROVED** [review]
These looks good to me. We do need to add tests for the HIP to our GPU CI, but I don't think that's a blocker now. It's a good idea to let users start playing with this platform, imo. Thanks!

**Comment by ijpulidos** [comment]
Since we have the openmm 8.2.0 rc in conda-forge should we test this PR with that rc? At least temporarily to run the CI with it. Maybe we actually need a workflow that runs CI with rc in general.

**Comment by mikemhenry** [comment]
Now that 8.2 is out, we can just double check things pass

**Comment by mikemhenry** [comment]
I've added 8.2.0 to the testing matrix and removed older openmm versions.

**Review by ijpulidos — APPROVED** [review]
Looks good to me. Thanks!

We need to write the tests to properly validate the platform but this is a great starting point.

**Pull request merged**
