### PR TITLE
0.20.1 Bugfix Release

### PR DESCRIPTION
**Pull request by mikemhenry**
## Description

This PR will be used for the 0.20.1 bugfix release

## Todos
- [ ] Implement feature / fix bug
- [ ] Add [tests](https://github.com/choderalab/openmmtools/tree/master/openmmtools/tests)
- [ ] Update [documentation](https://github.com/choderalab/openmmtools/tree/master/docs) as needed
- [ ] Update [changelog](https://github.com/choderalab/openmmtools/blob/master/docs/releasehistory.rst)Notable points that this PR has either accomplished or will accomplish.

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by mikemhenry** [comment]
Draft release here:
https://github.com/choderalab/openmmtools/releases/edit/untagged-bcbfb2bc61f77ec6a155

**Comment by jchodera** [comment]
This should go in before the bugfix release is cut!

I updated the release draft docs---thanks so much!

**Comment by mikemhenry** [comment]
I thought I needed to bump the version somewhere but it looks like `Versioneer`will take care of that for us when we tag the release.
@jaimergp do I need to tag this PR 0.21.1, then merge OR should I merge this PR then use the github gui to make the release?

**Comment by jaimergp** [comment]
The way I do it:

1. Prepare in a PR (this one) the needed changes (release notes, docs, etc)
2. Merge to `master`
3. Make sure everything looks alright (you AAAALWAYS forget about the README)
4. Locally, git pull master and create the corresponding tag with `git tag -a vX.Y`. Add a description there.
5. `git push --tags`
6. Use the GH GUI to create the release out of that newly pushed tag
7. CF will catch the release within the next hours

**Comment by mikemhenry** [comment]
Thanks @jaimergp ! I will document this in the wiki https://github.com/choderalab/openmmtools/wiki so that when I forgot how to do this and ask you again you can point me there :smile:

**Comment by jaimergp** [comment]
We forgot to remove the Cython import from setup.py 🤦

**Comment by mikemhenry** [comment]
Wow I should have caught that when playing with `Versioneer`

```
$ python setup.py version 
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
```

I will make another release!

**Pull request merged**
