### PR TITLE
Adding rRESPA and converting all integrators to classes.

### PR DESCRIPTION
**Pull request by jchodera**
Will need to finish converting integrators.py and tests.

### CODE REVIEW

**Comment by jchodera** [comment]
Addresses #34

**Comment by kyleabeauchamp** [comment]
So looks like the diff is pretty ugly from the way this conversion necessarily works (changes in tab structure).  Maybe you can briefly summarize how you changed things here in the discussion.

**Comment by kyleabeauchamp** [comment]
I wonder if it makes sense to dump `respa.py` into a separate file and add `from .respa import MTSIntegrator` in `integrators.py`.  That might help preserve the provenance information.

**Comment by jchodera** [comment]
OK, can do, but I need to do some gymnastics to make sure every integrator has default options (for testing purposes).

**Comment by jchodera** [comment]
> So looks like the diff is pretty ugly from the way this conversion necessarily works (changes in tab structure).

This is the drawback of using a language where spacing is an integral part of syntax.

>  Maybe you can briefly summarize how you changed things here in the discussion.

* The `MTSIntegrator` from `respa.py` was integrated (adding default options)
* All functions that used to return a `CustomIntegrator` object are now subclasses of `CustomIntegrator` whose constructor initializes the object
* Some minor cleanup to docstrings

I may need to tinker with the tests, but it looks like they should work.

**Comment by jchodera** [comment]
Seems like Python 3.x doesn't like the fact that this ratio can be a `float`:
https://github.com/choderalab/openmmtools/pull/36/files#diff-669299b3205f958c7662890143395b26R79

**Comment by jchodera** [comment]
Tests pass. This should be ready to merge.

**Pull request merged**
