### PR TITLE
0.20.4 Release

### PR DESCRIPTION
**Pull request by mikemhenry**

### CODE REVIEW

**Comment by mikemhenry** [comment]
Just waiting on https://github.com/choderalab/openmmtools/pull/538

**Comment by ijpulidos** [comment]
@mikemhenry Sorry for doing this again, but as discussed in #538 this is now a new "minor" release (0.21.0?) rather than a bugfix/patch release. Can you please change this PR to fix that, or make a new one? Thanks!!

**Comment by mikemhenry** [comment]
Can do! I'll use the UI to rename the branch and that *should* mean I don't have to close this one.

**Comment by mikemhenry** [comment]
Well using the UI didn't help, but that is okay!

**Pull request closed without merging**
