### PR TITLE
Update changelog for #511

### PR DESCRIPTION
**Pull request by Lnaden**
Update's changelog to reflect #511 changes.

## Description
Provide a brief description of the PR's purpose here.

## Todos
- [x] Implement feature / fix bug
- [x] Add [tests](https://github.com/choderalab/openmmtools/tree/master/openmmtools/tests)
- [x] Update [documentation](https://github.com/choderalab/openmmtools/tree/master/docs) as needed
- [x] Update [changelog](https://github.com/choderalab/openmmtools/blob/master/docs/releasehistory.rst)Notable points that this PR has either accomplished or will accomplish.

## Status
- [x] Ready to go

### CODE REVIEW

**Review by mikemhenry — APPROVED** [review]
Going to use this PR to update the changelog for the next release

**Comment by mikemhenry** [comment]
This too
https://github.com/choderalab/openmmtools/pull/535

**Review by jchodera — APPROVED** [review]
Thanks!

**Review by mikemhenry — CHANGES_REQUESTED** [review]
I think we got one more bugfix to get finished, then we can get the change log updated and a release out the door (sorry for hijacking this PR @Lnaden )

**Comment by Lnaden** [comment]
Its fine hijack away. What do you need me to do?

**Review by mikemhenry — APPROVED** [review]
Don't need you to do anything :) Thanks!

**Pull request merged**
