### PR TITLE
Optimization of CompoundThermodynamicState deserialization

### PR DESCRIPTION
**Pull request by andrrizzi**
As the title says.

### CODE REVIEW

**Comment by andrrizzi** [comment]
The failing doctest is being already fixed in #336 so this should be good to go!

**Comment by jchodera** [comment]
Do you need @Lnaden to review?

**Comment by jchodera** [comment]
Also, we probably want to cut a bugfix release when this is merged.

**Comment by andrrizzi** [comment]
I think he wanted to test this branch with YANK before reviewing/merging.

> Also, we probably want to cut a bugfix release when this is merged.

After this and #336 are merged, I'll cut a feature release.

**Comment by Lnaden** [comment]
Oh yes, this is MUCH faster Merging

**Pull request merged**
