### PR TITLE
Replace cython-accelerated all-swap replica mixing with numba implementation

### PR DESCRIPTION
**Pull request by jchodera**
## Description
This PR replaces the [`cython`](https://cython.org/) accelerated `all-swap` replica mixing scheme with a [`numba`](https://numba.pydata.org/) implementation.

The `cython` implementation not only caused installation issues, but is also suspected to potentially be causing the temperature issues in #480 and the MPI bug in #449 (but not yet proven to).

This implementation validates in a [test notebook](https://gist.github.com/jchodera/87149ea23530204d5b20913baa420ee3), and appears to be significantly faster:
* Python: 15 s
* cython: 4.1 s
* numba: 0.03 s

## Todos
- [x] Implement feature / fix bug
- [x] Add [tests](https://github.com/choderalab/openmmtools/tree/master/openmmtools/tests)
- [x] Update [documentation](https://github.com/choderalab/openmmtools/tree/master/docs) as needed
- [x] Update [changelog](https://github.com/choderalab/openmmtools/blob/master/docs/releasehistory.rst)Notable points that this PR has either accomplished or will accomplish.

## Status
- [ ] Ready to go

### CODE REVIEW

**Review by maxentile — COMMENTED** [review]
Woah, nice!

This looks like a big improvement in terms of performance, simplicity, readability, and safety. (I hadn't noticed the use of `drand48()` in `_mix_replicas.pyx` before looking at this PR, but in hindsight using a PRNG with 48-bit state seems risky when attempting so many permutations in a row...)

Regarding the current orders-of-magnitude performance difference compared to Cython, I suspect this might be due to different default `nswap_attempts` between the two implementations, although I bet Numba still has a significant performance advantage over Cython here.

(On my machine, if I change the `n_replicas=100` test so that Numba tries the same number `n_replicas**4` of swaps as Cython, then the apparent timing becomes something like: Numba 3.5s vs. Cython 5.0s.)

**Comment by jchodera** [comment]
Good catch!

Hm, I think the right thing to do here is to set a maximum runtime for `mix_replicas()` (e.g. 0.1 s) since the whole point is just to mix replicas as thoroughly as possible without slowing things down.

**Comment by jchodera** [comment]
@maxentile : Looks like it's not easy to do timing within a numba jitted function, so I've just equalized the number of swap attempts to `n_replicas**3` and (hopefully) fixed the test env error.

**Comment by jchodera** [comment]
I wonder why the context cache is trying to use OpenCL on `osx`---I don't see anything that should be trying to do that:
```
======================================================================
ERROR: Test configuration of the context cache.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/miniconda/envs/test/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/runner/work/openmmtools/openmmtools/openmmtools/tests/test_mcmc.py", line 251, in test_context_cache
    move.apply(thermodynamic_state, sampler_state)
  File "/Users/runner/work/openmmtools/openmmtools/openmmtools/mcmc.py", line 1114, in apply
    super(LangevinDynamicsMove, self).apply(thermodynamic_state, sampler_state)
  File "/Users/runner/work/openmmtools/openmmtools/openmmtools/mcmc.py", line 655, in apply
    context, integrator = context_cache.get_context(thermodynamic_state, integrator)
  File "/Users/runner/work/openmmtools/openmmtools/openmmtools/cache.py", line 754, in get_context
    context = thermodynamic_state.create_context(integrator, self.platform)
  File "/Users/runner/work/openmmtools/openmmtools/openmmtools/states.py", line 1174, in create_context
    return openmm.Context(system, integrator, platform)
  File "/usr/local/miniconda/envs/test/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 6270, in __init__
    this = _openmm.new_Context(*args)
Exception: No compatible OpenCL platform is available

======================================================================
ERROR: ThermodynamicState.create_context() method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/miniconda/envs/test/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/runner/work/openmmtools/openmmtools/openmmtools/tests/test_states.py", line 648, in test_method_create_context
    context = state.create_context(integrator, platform)
  File "/Users/runner/work/openmmtools/openmmtools/openmmtools/states.py", line 1174, in create_context
    return openmm.Context(system, integrator, platform)
  File "/usr/local/miniconda/envs/test/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 6270, in __init__
    this = _openmm.new_Context(*args)
Exception: No compatible OpenCL platform is available
```

**Comment by jchodera** [comment]
There are a ton of windows failures that all seem to be due to issues with [`openmmtools.utils.temporary_directory()`](https://github.com/choderalab/openmmtools/blob/master/openmmtools/utils.py#L43-L50) on win:
```
======================================================================
ERROR: Test that checkpoint and storage files have the same UUID
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda\envs\test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "D:\a\openmmtools\openmmtools\openmmtools\tests\test_sampling.py", line 1317, in test_checkpoint_uuid_matching
    assert reporter._storage_checkpoint.UUID == reporter._storage_analysis.UUID
  File "C:\Miniconda\envs\test\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "D:\a\openmmtools\openmmtools\openmmtools\tests\test_sampling.py", line 679, in temporary_storage_path
    yield storage_file_path
  File "C:\Miniconda\envs\test\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "D:\a\openmmtools\openmmtools\openmmtools\utils.py", line 50, in temporary_directory
    shutil.rmtree(tmp_dir)
  File "C:\Miniconda\envs\test\lib\shutil.py", line 500, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Miniconda\envs\test\lib\shutil.py", line 395, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Miniconda\envs\test\lib\shutil.py", line 393, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmp9a_kqqgb\\checkpoint_file.nc'
-------------------- >> begin captured logging << --------------------
```
@jaimergp : Any insights on this one? Seems like it should be simple to fix.

**Comment by jchodera** [comment]
Let's deal with the `osx` and `win` failures in a separate PR.

**Pull request merged**
