### PR TITLE
Porting multistates from yank to openmmtools

### PR DESCRIPTION
**Pull request by hannahbrucemacdonald**
- [x] Implement feature / fix bug
 - [x] Add [tests](https://github.com/choderalab/openmmtools/tree/master/openmmtools/tests)
 - [ ] Update [documentation](https://github.com/choderalab/openmmtools/tree/master/docs) as needed
 - [ ] Update [changelog](https://github.com/choderalab/openmmtools/blob/master/docs/releasehistory.rst)

test_sampling.py and test_mixing.py have been moved

forked repo failing for py3.5 as pulling down outdated opemmtools-dev, but this should disappear in main repo

### CODE REVIEW

**Comment by jchodera** [comment]
Excited to see this moving ahead!

**Comment by jchodera** [comment]
I think the documentation may not have been set up yet. From what I can tell, you'll need to update [`sampling.rst`](https://github.com/choderalab/openmmtools/blob/0921b3b59ccf390008fcdeb49b32b6d1f6d6954e/docs/sampling.rst) to be similar to what we have for, say, [`mcmc.rst`](https://raw.githubusercontent.com/choderalab/openmmtools/0921b3b59ccf390008fcdeb49b32b6d1f6d6954e/docs/mcmc.rst)
* Make sure the dependencies in [`docs/environment.yml`](https://github.com/choderalab/openmmtools/blob/0921b3b59ccf390008fcdeb49b32b6d1f6d6954e/docs/environment.yml) are updated too so that readthedocs can install openmmtools and render the docs

**Comment by jchodera** [comment]
@andrrizzi : Did you want to get that offset PME feature release out before this gets merged?

**Comment by hannahbrucemacdonald** [comment]
> I think the documentation may not have been set up yet. From what I can tell, you'll need to
> 
> * update [`sampling.rst`](https://github.com/choderalab/openmmtools/blob/0921b3b59ccf390008fcdeb49b32b6d1f6d6954e/docs/sampling.rst) to be similar to what we have for, say, [`mcmc.rst`](https://raw.githubusercontent.com/choderalab/openmmtools/0921b3b59ccf390008fcdeb49b32b6d1f6d6954e/docs/mcmc.rst)
> * make sure the dependencies in [`docs/environment.yml`](https://github.com/choderalab/openmmtools/blob/0921b3b59ccf390008fcdeb49b32b6d1f6d6954e/docs/environment.yml) are updated too so that readthedocs can install openmmtools and render the docs

Ah sorry will fix that.

Not sure how to deal with the appveyor failure, but will dig in to that!

**Comment by andrrizzi** [comment]
Thanks! Will review ASAP!

> @andrrizzi : Did you want to get that offset PME feature release out before this gets merged?

That's probably a good idea! I'll make a release today.

**Comment by andrrizzi** [comment]
Hmm. For some reason Travis with Python 3.5 is downloading the `openmmtools-dev` from the `omnia` channel rather than using the local install: https://travis-ci.org/choderalab/openmmtools/jobs/483592137#L1474

There may be a version conflict for Python 3.5 with the current conda recipe.

**Comment by jchodera** [comment]
@andrizzi: 
* We now only support python 3.6 and 3.7 to match conda-forge
* I can delete that dev package from the channel since dev packages now live in the omnia-dev channel, but I imagine all you have to do is change the recipe name in devtools

**Comment by andrrizzi** [comment]
Right, thanks! I'll try to fix this before getting the release out.

**Pull request closed without merging**
