### PR TITLE
[WIP] Extra Chance (G)HMC

### PR DESCRIPTION
**Pull request by maxentile**
- [x] Implement feature / fix bug
 - [ ] Add [tests](https://github.com/choderalab/openmmtools/tree/master/openmmtools/tests)
 - [ ] Update [documentation](https://github.com/choderalab/openmmtools/tree/master/docs) as needed
 - [ ] Update [changelog](https://github.com/choderalab/openmmtools/blob/master/docs/releasehistory.rst)

Pulling in the Extra-Chance (G)HMC integrators @kyleabeauchamp has implemented, as a separate module from the `integrators` module.

### CODE REVIEW

**Comment by maxentile** [comment]
I don't have permissions to push commits directly onto this branch, so I'll be working on them here https://github.com/choderalab/openmmtools/tree/pr/355 and request a review when ready.

**Comment by kyleabeauchamp** [comment]
Would it make things easier if I just pushed my openmmtools fork into a choderalab branch that you can edit?

**Comment by maxentile** [comment]
Oh, actually that would be ideal! Thanks!

**Comment by maxentile** [comment]
Will close this one also.

**Pull request closed without merging**
