### PR TITLE
Charged LJ Fluid, Ewald tolerance, FCC grid

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
1.  Allow alternating plus and minus charges in LJ fluid for testing PME in a simple liquid system
2.  Allow setting of Ewald tolerance in LJ Fluid and WaterBox
3.  Allow LJ Fluid to use a FCC grid for starting coordinates, which can be useful when trying to get a liquid testsystem that doesn't require pressure equilibration.

### CODE REVIEW

**Comment by jchodera** [comment]
Awesome.  Apologies for removing the grid code before---I thought that the subrandom initial conditions would be superior and allow any number of particles, but that doesn't appear to have been the case.

**Comment by jchodera** [comment]
Is that really an FCC lattice, or just a primitive cubic lattice?

**Comment by kyleabeauchamp** [comment]
Here is a screenshot from pymol of the nearest neighbors of a point.  The coordination number is 12, which should indicate FCC:

coord

**Comment by kyleabeauchamp** [comment]
OK, the only travis failure is src explicit again.

**Pull request merged**
